---
- name: install jdk
  apt: 
    name: "{{jdk_pkg}}"
    state: present
    update_cache: yes
  become: yes
- name: setup java home evnroniment
  shell: readlink -f $(which java) | sed 's/bin.*//g'
  register: java_home 
