---
- name: download tomcat
  get_url:
    url: "{{tomcat_download_url}}"
    dest: "/tmp/{{tomcat_download_dir}}.tar.gz"
    mode: "0755"
    
    owner: "{{tomcat_os_user}}"
    group: "{{tomcat_os_group}}"
  become: yes
- name: unzip tomcat file
  unarchive:
    src: "/tmp/{{tomcat_download_dir}}.tar.gz"
    dest: "/tmp/"
    mode: "0755"
    remote_src: yes
  become: yes
- name: copy and install tomcat10
  copy:
    src: "/tmp/{{tomcat_download_dir}}/"
    dest: "{{tomcat_install_dir}}/{{tomcat_dir}}/"
    owner: "{{tomcat_os_user}}"
    group: "{{tomcat_os_group}}"
    mode: "0755"
    
    
    remote_src: yes
  
  become: yes
